docs/decisions/0001-purpose-of-this-repo.rst

Update ADR 0001 that describes the purpose of this repository.
**JIRA:** N/A
**Dependencies:** [event-tracking](https://github.com/edx/event-tracking) 
**Merge deadline:** N/A
**Installation instructions:** N/A
**Testing instructions:** N/A
**Reviewers:**
finished.
**Author concerns:** N/A

Add ADR 0001 for purpose of this repo

---

docs/decisions/0003-router-configurations-storage.rst

Add ADR 0003 that describes the medium we will be using for storing the router configurations.
**JIRA:** N/A
**Dependencies:** [event-tracking](https://github.com/edx/event-tracking) 
**Merge deadline:** N/A
**Installation instructions:** N/A
**Testing instructions:** N/A
**Reviewers:**
finished.
**Author concerns:** N/A

Add ADR 0003 medium for router configurations storage

---

docs/decisions/0001-purpose-of-this-repo.rst
docs/decisions/0002-binding-app-for-caliper.rst
docs/decisions/0003-router-configurations-storage.rst

**Description:** Updates the ADR's status in #1 ,#2, #3  to `Approved`
**JIRA:** N/A
**Dependencies:** None
**Merge deadline:** N/A
**Installation instructions:** N/A
N/A
**Reviewers:**
finished.

Update ADRs status to Approved

---

docs/howto/how_to_test.rst

instructions.
1. Open page A
2. Do thing B
finished.

Adding a rough how to test locally doc

---

docs/howto/how_to_test.rst

instructions.
1. Open page A
2. Do thing B
finished.

fixing quality

---

README.rst

Condense overview and link OEP-26

---

event_routing_backends/__init__.py

Considering the amount of changes that occured in #11, I think a major version bump is warranted. Let me know if you think otherwise.

Major version bump

---

requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt

bump the version
instructions.
1. Open page A
2. Do thing B
finished.

run makeu pgrade.

---

CHANGELOG.rst
docs/howto/how_to_test.rst
event_routing_backends/__init__.py
event_routing_backends/processors/caliper/__init__.py
event_routing_backends/processors/caliper/tests/test_caliper.py
event_routing_backends/processors/caliper/transformer_processor.py
event_routing_backends/processors/xapi/__init__.py
event_routing_backends/processors/xapi/tests/test_xapi.py
event_routing_backends/processors/xapi/transformer_processor.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

Add settings to safeguard against accidental enabling of Caliper/xAPI

---

docs/decisions/0004-transformers-architecture.md

Add ADR for decision about developing Transformers as "Processors"
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 

Add ADR for transformer architecture

---

event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.enrollment.activated.enterprise.json
event_routing_backends/processors/caliper/transformer.py
event_routing_backends/processors/mixins/base_transformer.py
event_routing_backends/processors/tests/fixtures/current/edx.course.enrollment.activated.enterprise.json
event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
event_routing_backends/processors/xapi/event_transformers/navigation_events.py
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
event_routing_backends/processors/xapi/event_transformers/video_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.activated.enterprise.json
event_routing_backends/processors/xapi/transformer.py

instructions.
1. Open page A
2. Do thing B
finished.

get username from data dict if not available in context dict of event

---

event_routing_backends/processors/mixins/base_transformer.py

**Description:** Updated the documentation of ``get_data`` method.

docs: updated docstring of get_data method in base_transfromer.py

---

event_routing_backends/processors/caliper/event_transformers/enrollment_events.py
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.completed.json
event_routing_backends/processors/tests/fixtures/current/edx.course.completed.json
event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
event_routing_backends/processors/xapi/event_transformers/navigation_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.completed.json

**Description:** Added a new event transfarmer for course completion event in both xAPI and Caliper and added fixtures for testing these transformers
instructions.
1. Open page A
2. Do thing B
finished.

feat: Added course completion event transformer

---

event_routing_backends/processors/mixins/base_transformer.py
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py

**Description:** Find nested keys from common accessor method get data to ensure a single access point for all event data
instructions.
1. Open page A
2. Do thing B
finished.

Refactor: Find nested keys from common accessor method get data

---

docs/decisions/0005-PII-leakage-prevention.rst

**Description:** added link of accessor method in ADR

[ERTE-15-1] docs: added link of accessor method

---

event_routing_backends/processors/xapi/constants.py
event_routing_backends/processors/xapi/transformer.py

**Description:** Added transformer version in XAPI transformed events. Version is set in a constant 
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-36
instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-36] feat: Added transformer version in XAPI transformed events

---

.github/workflows/ci.yml
CHANGELOG.rst
event_routing_backends/__init__.py
setup.py
tox.ini

JIRA: https://openedx.atlassian.net/browse/BOM-2631

feat: Added support for django3.2

---

event_routing_backends/models.py
event_routing_backends/tests/test_mixin.py
event_routing_backends/tests/test_models.py

**Description:** Updated the method _match_event_for_host to incorporate list search d regex match
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-38
instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-38] feat: Updated the method _match_event_for_host to incorporate list search and regex match

---

docs/decisions/0007-access-control-of-events.rst
docs/event-mapping/list_of_supported_edx_events.rst

**Description:** Created ADR for access control of events
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-32?atlOrigin=eyJpIjoiMDMwZTRjNzYzNmRlNDUzY2E2MzU5ZjUwZWVkYTdlMzQiLCJwIjoiaiJ9

[ERTE-32] docs: Created an ADR for access control of events

---

celeryconfig.py
event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/tasks.py
requirements/base.in
test_settings.py

instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-66] feat: Created separate celery tasks per recipient per event

---

event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/helpers.py
event_routing_backends/tasks.py

instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-82] feat: Setup list of business critical event and persist those

---

event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/utils/xapi_lrs_client.py

instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-67] Refactor: Integration and testing with mock LRS

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

**Description:** Fix failing make upgrade job due to version conflicts
**JIRA:** https://openedx.atlassian.net/browse/BOM-2780

BOM-2780: Fix make upgrade

---

event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/processors/caliper/tests/test_caliper.py
event_routing_backends/processors/caliper/transformer_processor.py
event_routing_backends/processors/mixins/base_transformer_processor.py
event_routing_backends/processors/transformer_utils/exceptions.py
event_routing_backends/processors/transformer_utils/registry.py
event_routing_backends/processors/xapi/tests/test_xapi.py
event_routing_backends/processors/xapi/transformer_processor.py
event_routing_backends/tasks.py
event_routing_backends/utils/xapi_lrs_client.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

**Description:** Add details in logs where EventEmissionExit is raised to distinguish between exceptions.
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-61
instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-61] Refactor: Add details in logs where EventEmissionExit is raised to distinguish between exceptions.

---

event_routing_backends/processors/xapi/event_transformers/video_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/complete_video(proposed).json
event_routing_backends/processors/xapi/tests/fixtures/expected/load_video.json
event_routing_backends/processors/xapi/tests/fixtures/expected/pause_video.json
event_routing_backends/processors/xapi/tests/fixtures/expected/play_video.json
event_routing_backends/processors/xapi/tests/fixtures/expected/seek_video.json
event_routing_backends/processors/xapi/tests/fixtures/expected/stop_video.json

instructions.
1. Open page A
2. Do thing B
finished.

feat: Remove 'code' field from transformed xAPI video events' extensions.

---

docs/getting_started.rst

**Description:** updated event_routing_backends application setup procedure
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-84

[ERTE-84] docs: updated application setup procedure

---

event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/utils/http_client.py

instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-83] feat: added username, password authentication support in http client

---

event_routing_backends/helpers.py
event_routing_backends/processors/caliper/transformer.py
event_routing_backends/processors/mixins/base_transformer.py
event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
event_routing_backends/processors/xapi/event_transformers/navigation_events.py
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
event_routing_backends/processors/xapi/event_transformers/video_events.py
event_routing_backends/processors/xapi/transformer.py
event_routing_backends/tasks.py
event_routing_backends/tests/test_helpers.py

instructions.
1. Open page A
2. Do thing B
finished.

feat: added ablity to get anonymous user_id either by username or user_id

---

event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py

instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-89] feat: Added support for multiple routers host configurations

---

event_routing_backends/backends/tests/test_events_router.py

**Description:** Added Test case for multiple routers against a backend
instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-89] Refactor: Added Test case for multiple event routers

---

event_routing_backends/__init__.py
event_routing_backends/settings/common.py

instructions.
1. Open page A
2. Do thing B
finished.

[ERTE-110] feat: Added Video completion event in common settings

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

- Ran `make upgrade` manually to resolve the pip & pip-tools conflict during the upgrade job.

chore: upgrade python requirements

---

requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

Scheduled requirements upgrade workflow [build](https://github.com/openedx/event-routing-backends/actions/runs/3279034402/jobs/5398102969) failed to create PR so creating the PR manually.

chore: Updating Python Requirements

---

docs/decisions/0006-versioning-of-event-transformers.rst

**Description:** Updates an implementation detail in ADR-0006 regarding the name and format of the version. This is a docs-only update, to be followed up with an implementation change to enact it.

docs: Update ADR-0006 for transformerVersion change

---

event_routing_backends/__init__.py

**Description:** Version bump to 5.5.0 for next release

chore: Bump version to 5.5.0

---

CHANGELOG.rst
event_routing_backends/__init__.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

https://github.com/MichelML/django-fernet-fields
https://pypi.org/project/django-fernet-fields-v2/

chore: upgrading deprecated `djfernet` with `django-fernet-fields-v2`.

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/management/commands/helpers/queued_sender.py
event_routing_backends/management/commands/tests/test_transform_tracking_logs.py
test_settings.py

**Description:** This PR uses the already configured backends to replay tracking logs
finished.

feat: allow to use any configured engine to replay tracking logs

---

event_routing_backends/__init__.py

chore: version bump

---

CHANGELOG.rst
event_routing_backends/__init__.py

Bump version after latest fixes.

chore: bump version to v9.3.2

---

.github/workflows/ci.yml
CHANGELOG.rst
event_routing_backends/__init__.py
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
setup.py
tox.ini

https://github.com/openedx/event-routing-backends/issues/498

feat!: Adding django5.2 support.
