openedx/event-routing-backends

docs/decisions/0002-binding-app-for-caliper.rst

Add ADR 0002 that describes why we are not using the IMS [caliper-python](https://github.com/IMSGlobal/caliper-python) app for caliper events binding and instead will be using python dictionaries.
**JIRA:** N/A
**Dependencies:** [event-tracking](https://github.com/edx/event-tracking) 
**Merge deadline:** N/A
**Installation instructions:** N/A
**Testing instructions:** N/A
**Reviewers:**
finished.
**Author concerns:** N/A

Add ADR 0002 binding app for caliper

---

docs/getting_started.rst

- Highlight config example as Python, not JSON, and use single quotes to
match our convention
- Specify backend name to use for JSON config block
- Indicate which files and environments to make the changes and run the
commands in
- Use example.com for any example URLs
- Indentation and other minor syntax cleanups

Fixes to "Getting Started" documentation

---

.github/workflows/publish_pypi.yml

Fix use of secret for PyPI publishing

---

CHANGELOG.rst
docs/howto/how_to_test.rst
event_routing_backends/__init__.py
event_routing_backends/processors/caliper/constants.py
event_routing_backends/processors/caliper/envelop_processor.py
event_routing_backends/processors/caliper/tests/fixtures/expected/complete_video(proposed).json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.enrollment.activated.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.enrollment.deactivated.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.grades.problem.submitted.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.problem.completed(proposed).json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.problem.hint.demandhint_displayed.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.link_clicked(anonymous_user).json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.link_clicked.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.outline.selected.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.sequence.next_selected.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.sequence.previous_selected.json
event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.sequence.tab_selected.json
event_routing_backends/processors/caliper/tests/fixtures/expected/load_video.json
event_routing_backends/processors/caliper/tests/fixtures/expected/pause_video.json
event_routing_backends/processors/caliper/tests/fixtures/expected/play_video.json
event_routing_backends/processors/caliper/tests/fixtures/expected/problem_check(browser).json
event_routing_backends/processors/caliper/tests/fixtures/expected/problem_check(server).json
event_routing_backends/processors/caliper/tests/fixtures/expected/seek_video.json
event_routing_backends/processors/caliper/tests/fixtures/expected/showanswer.json
event_routing_backends/processors/caliper/tests/fixtures/expected/stop_video.json
event_routing_backends/processors/caliper/tests/test_envelop_processor.py

Changes:
Adding more directions for local testing
Changed how data is structured:
before:
`data: {}`
after:
`data: [{}]`
Changed url to point to newest specification.

Modifying implementation to match caliper specification

---

CHANGELOG.rst
docs/getting_started.rst
event_routing_backends/__init__.py
event_routing_backends/processors/caliper/envelope_processor.py
event_routing_backends/processors/caliper/tests/test_envelope_processor.py
event_routing_backends/processors/caliper/transformer.py
event_routing_backends/processors/caliper/transformer_processor.py
event_routing_backends/processors/mixins/base_transformer.py
event_routing_backends/processors/mixins/base_transformer_processor.py
event_routing_backends/processors/xapi/transformer_processor.py

BREAKING CHANGE: Rename CaliperEnvelopeProcessor (and module) to fix typo.
This will require updating the config on any Caliper test environment.

Fix typo in class & module name, also in some comments and docstrings

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/processors/transformer_utils/registry.py

Change a noisy INFO log message in TransformerRegistry.register() to DEBUG and fix two logging typos.

Version 4.0.1 | DEBUG instead of INFO

---

event_routing_backends/processors/caliper/__init__.py
event_routing_backends/processors/xapi/__init__.py

We'll want to keep these toggles because eventing is going to place
different loads on the system, and we may need to be able to shut off
external eventing in a coarse-grained way due to operational emergencies.
Also, fix creation date of toggles.

doc: Indicate that events toggles are permanent

---

tox.ini

- Remove `tests/__init__.py`
- Remove `touch` and `rm` from tox.ini `testenv:quality` env
- Remove `tests` as an argument to quality checker commands
Running tests was causing the working tree to become dirty -- I think the
`tests/__init__.py` file was checked in by mistake at some point. But the
whole `touch`/`rm` mechanism was only needed to make sure the `tests` dir
existed because various commands tried to run quality checks on it
explicitly. This removes it as a quality target because it's otherwise
an empty directory.

test: Delete unused tests dir

---

event_routing_backends/processors/caliper/event_transformers/problem_interaction_events.py
event_routing_backends/processors/caliper/event_transformers/video_events.py
event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
event_routing_backends/processors/xapi/event_transformers/navigation_events.py
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
event_routing_backends/processors/xapi/event_transformers/video_events.py

find_nested method performs a depth first search of key in given dict.
we are using this method to search keys in the event data.
If event has some keys with same name using this method can result in
finding/passing irrelevent and/or non scalar data.
These changes limit usage of `find_nested` to only those places
where we don't have absolute path of keys to find and we have type safety checks inplace.

refactor: limit find_nested usage

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

**Issue:** [BOM-2558](https://openedx.atlassian.net/browse/BOM-2558)
- celery requires [click<8.0](https://github.com/celery/celery/blob/master/requirements/default.txt#L5) which causes version conflicts when running [requirement upgrade build](https://github.com/edx/event-routing-backends/runs/2671928810?check_suite_focus=true). 
- The constraint may be removed once the issue https://github.com/celery/celery/issues/6753 is fixed.

BOM-2558: Pin click<8.0 version

---

docs/decisions/0005-PII-leakage-prevention.rst

**Description:** A new accessor method named ``get_data`` will be used to access information in the edx event. This will help spot any potential PII leakage via transformers, during code review. This ADR is to inform community and developers about this approach.
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-15

ADR for an accessor method to reduce chances of PII leakage

---

docs/decisions/0006-versioning-of-event-transformers.rst

**Description:** An ADR has been added to explain the versioning scheme of xAPI and Caliper transformers.
**JIRA:** https://edlyio.atlassian.net/browse/ERTE-20

An ADR for versioning of xAPI and Caliper transformers

---

docs/event-mapping/list_of_supported_edx_events.rst

**Description:** Updated list of supported events. `edx.video.completed` is omitted from the list because it is not being currently emitted by edx platform.

docs: updated list of events

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

Description:
We’d pinned the click version because of celery. Now the new version of celery has bumped the required click constraint so we can remove the click constraint from the constraints.txt file.

Unpin click version

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

`edx-celeryutils` has been upgraded and the required `click` constraint has been removed from it so the `click` constraint can be removed now to allow the `make upgrade` job to pass.

Remove click constraint to fix make upgrade job

---

CHANGELOG.rst
event_routing_backends/settings/common.py

White listing `video_complete` event for xAPI backend.

feat: whitelisted video complete event for xAPI backend

---

Makefile
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt

Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this https://github.com/openedx/edx-repo-health/pull/271 for new check added in edx-repo-health.
JIRA: https://2u-internal.atlassian.net/browse/BOM-3457

fix: Install pip and pip-tools in upgrade script

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

- `Sphinx` requires `docutils` and `doc8` pinned versions for the `make upgrade` job to pass.

fix: pin doc8 and docutils versions

---

CHANGELOG.rst
docs/event-mapping/Caliper_mapping.rst
docs/event-mapping/xAPI_mapping.rst
event_routing_backends/helpers.py
event_routing_backends/processors/caliper/event_transformers/problem_interaction_events.py
event_routing_backends/processors/caliper/transformer.py
event_routing_backends/processors/xapi/transformer.py
event_routing_backends/tests/test_helpers.py
test_utils/__init__.py

This PR has changes to use `LTI` and `CALIPER` externalId types instead of `LTI`.

feat: use appropriate externalId types

---

requirements/base.txt
requirements/ci.in
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

**Description:** codecov pulled their entire PyPI project and everything broke. We didn't actually need it, since we're using the Github action to upload these days. Also running make upgrade to propagate the change.

chore: Remove broken codecov requirement, run upgrade

---

CHANGELOG.rst
event_routing_backends/helpers.py
event_routing_backends/processors/tests/transformers_test_mixin.py
event_routing_backends/processors/xapi/tests/test_transformers.py
event_routing_backends/processors/xapi/transformer.py
event_routing_backends/settings/common.py
event_routing_backends/settings/production.py
event_routing_backends/tests/test_helpers.py
test_settings.py
test_utils/__init__.py

This PR has changes to make user identifier in xAPI events configurable. We have introduced a new setting `XAPI_AGENT_IFI_TYPE` to make it configurable.
This setting can be used to specify the type of inverse functional identifier for actor in xAPI statements. Possible values are `external_id`, `mbox_sha1sum` and `mbox`
when we set it to `external_id` xAPI statement would represent actor like this
```
{
"objectType": "Agent",
"account": {"homePage": "http://localhost:18000", "name": "32e08e30-f8ae-4ce2-94a8-c2bfe38a70cb"}
}
```
setting it to `mbox` xAPI statement would represent actor like this
```
{
"objectType": "Agent",
"mbox": "mailto:info@xapi.com"
}
```
setting it to `mbox_sha1sum` xAPI statement would represent actor like this
```
{
"objectType": "Agent",
"mbox_sha1sum": …
```

feat: Make xAPI User Identifier configurable

---

event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py

**Description:** Downgrade log level from **error** to **info** when there is not router configuration for the given backend.
**Issue:** It solves #289 and #287

fix: downgrade log level when no routers configuration

---

event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/utils/xapi_lrs_client.py

**Description:** The 409 error code is returned when an LRS determines a statement id already exists in the database, which is a use case we will see a lot with the new idempotent statement ids and upcoming tracking log replay. This change logs and eats that error.
This was introduced here:
https://github.com/openedx/event-routing-backends/pull/290/files
**Issue:** https://github.com/openedx/event-routing-backends/issues/295
**Merge deadline:** ASAP as this has a multiplicative effect for each failing event which (in older versions) is compounded by this issue: https://github.com/openedx/event-routing-backends/issues/296
Currently this is easy to test in a Nutmeg Tutor install given the other issue with the idempotent ids.  …

fix: Many retries when an LRS returns a 409 error

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/helpers.py

**Description:** Older edx-platform versions don't have the XAPI and Caliper types, causing errors. This allows a graceful fallback.
**Issues:** #296 #297
1. Try to send an xAPI event on a Nutmeg server with e-r-b installed
2. Note the errors in the log: `Error: type object 'ExternalIdType' has no attribute 'XAPI'`
finished.
**Author concerns:** This solution is pretty hacky, we should really make a setting or something to force LTI type in case anyone using this wants to upgrade later and not have all of their actor ids change. Test isn't written to cover this try / catch, I'm not sure it's worth the time.

fix: Allow LTI fallback on ExternalIdTypes for older edx-platform versions

---

CHANGELOG.rst
docs/event-mapping/Supported_events.rst
docs/event-mapping/xAPI_mapping.rst
event_routing_backends/__init__.py
event_routing_backends/processors/tests/fixtures/current/edx.course.enrollment.mode_changed.json
event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.mode_changed.json
event_routing_backends/settings/common.py

**Description:** Add support for the `edx.course.enrollment.mode_changed` event. Use the same verb and transformer than `edx.course.enrollment.activated`
Verb
```Javacript
XAPI_VERB_REGISTERED = 'http://adlnet.gov/expapi/verbs/registered'
```
Closes #292 

Add support for the edx.course.enrollment.mode_changed event

---

event_routing_backends/__init__.py
event_routing_backends/processors/caliper/event_transformers/video_events.py
event_routing_backends/processors/tests/fixtures/current/edx.video.closed_captions.hidden.null.duration.json

**Description:** Fixes https://github.com/openedx/event-routing-backends/issues/310 which was reported here: https://github.com/openedx/event-routing-backends/pull/301#pullrequestreview-1487368033
**Author concerns:** I wasn't able to test this, or write a new test for it since it seems like an existing test should have already caught this. I'm not quite sure what the difference was in @ziafazal 's test, but this change seems harmless and obviously worked for him.

fix: Caliper transform of video events without duration

---

.github/workflows/ci.yml
event_routing_backends/__init__.py
event_routing_backends/admin.py
setup.py
tox.ini

**Issue:** https://github.com/edx/upgrades/issues/151
instructions.
1. Open page A
2. Do thing B
finished.

feat: upgrade to Django 4.2

---

event_routing_backends/__init__.py
event_routing_backends/processors/tests/fixtures/current/edx.grades.problem.submitted.weighted_possible_0.json
event_routing_backends/processors/tests/fixtures/current/problem_check(server).max_grade_0.json
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.grades.problem.submitted.weighted_possible_0.json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server).max_grade_0.json

**Description:** Some fields in the wild have unexpected 0 values, leading to "divide by 0" errors on transform. This PR handles them somewhat more elegantly.
Closes: #311

fix: Divide by 0 errors on problem interaction events

---

event_routing_backends/__init__.py
event_routing_backends/processors/tests/fixtures/current/edx.grades.problem.submitted.weighted_possible_null.json
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py

instructions.
1. Open page A
2. Do thing B
finished.

fix: catch null weighted_possible

---

event_routing_backends/__init__.py
event_routing_backends/management/commands/tests/test_transform_tracking_logs.py
event_routing_backends/management/commands/transform_tracking_logs.py
event_routing_backends/settings/common.py

**Description:** Forces retries when errors occur downloading tracking log chunks in bulk transform.
Fixes: #329

fix: Retry getting bulk tracking logs

---

CHANGELOG.rst
docs/event-mapping/Supported_events.rst
event_routing_backends/__init__.py
event_routing_backends/processors/tests/fixtures/current/edx.completion.block_completion.changed.json
event_routing_backends/processors/xapi/constants.py
event_routing_backends/processors/xapi/event_transformers/__init__.py
event_routing_backends/processors/xapi/event_transformers/completion_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.completion.block_completion.changed.json
event_routing_backends/settings/common.py

**Description:** Adds an xAPI transformer for completion events
**Dependencies:** https://github.com/openedx/completion/pull/245
instructions.
1. Open page A
2. Do thing B
finished.

feat: add xapi transformer for completion events

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/helpers.py
event_routing_backends/tests/test_helpers.py

**Description:**  A setting to allow to send missing courses
instructions.
1. Open page A
2. Do thing B
finished.

fix: block events for missing courses

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/processors/tests/fixtures/current/problem_check(server).list_answers.json
event_routing_backends/processors/tests/transformers_test_mixin.py
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server).json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server).list_answers.json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server).max_grade_0.json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server,multiple_questions,correct).json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server,multiple_questions,incorrect).json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server,multiple_questions,partial_correct).json
event_routing_backends/processors/xapi/tests/test_xapi_event_transformers.py

Prior to this fix, TinCan would use the repr of the list, which made some responses effectively un-parseable downstream.
closes #365 
finished.
**Author concerns:** This is a bit of a hack around TinCan, and also TinCan hasn't been updated in 3 yrs. We should consider forking it or replacing it. 😬

fix: Serialize list problem_check results as JSON

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/helpers.py
event_routing_backends/tests/test_helpers.py
setup.cfg

When a user sets their username as a numeric value, for example the local id (1022547854), the current code handles this as the user id  therefore the right user is not found and that returns None, This changes add support for that specific case and includes some basic unit tests which validates the basic behavior 
1. Create a user with an username like "1100865375"
2. Set a problem, example multiple choices
3. Attempt previous problem 
4. check logs, the message  `User with username "1100865375" does not exist.` shouldn't appear 
or directly call the method in a shell 
finished. …

fix: support numeric usernames on get_user method

---

.readthedocs.yaml
CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/processors/openedx_filters/decorators.py
event_routing_backends/processors/openedx_filters/filters.py
event_routing_backends/processors/tests/openedx_filters/test_filters.py
setup.cfg

This improves the filter usability by adding the transformer to the filter arguments, basically this allows the filter client to access to extra data given by the transformer instance.
Current implementation just pass as argument the result of the decorated method, for example, the activity returned by this [method](https://github.com/openedx/event-routing-backends/blob/master/event_routing_backends/processors/xapi/event_transformers/enrollment_events.py#L30) however that activity or another result has limited information, for this example the filler would have something like 
```
"object":{
"id":"https://example.com/course/course-v1:edx+cs105+101_2023",
"definition":{
"name":{
"en":" testing-course "
},
"type":"http://adlnet.gov/expapi/activities/course",
"extensions":{ …
```

feat!: add transformer to filter arguments.

---

requirements/base.txt
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

- Remove `tox-battery` from requirements since it is not needed for `tox>3` anymore.
- Updated `tox` to `v4`.

fix: remove tox-battery requirement and update tox

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/helpers.py
event_routing_backends/processors/tests/fixtures/current/play_video.ccx.json
event_routing_backends/processors/tests/fixtures/current/problem_check(browser).ccx.json
event_routing_backends/processors/xapi/tests/fixtures/expected/play_video.ccx.json
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(browser).ccx.json

**Description:** This PR dinamically gets the block-id version from the `block_id` string. Support CCX courses.
1. Enable CCX courses
2. Configure a Course as a CCX master
3. Create a CCX child course
4. Emit a video event and a problem event
5. Make sure the corresponding xAPI event has the block ID serialized correctly, verifying that the `object.id` URL points to the right CCX object.

fix: dinamically get the block-id version

---

CHANGELOG.rst
docs/event-mapping/Supported_events.rst
event_routing_backends/__init__.py
event_routing_backends/settings/common.py

instructions.
1. Open page A
2. Do thing B
finished.

fix: add grade.now* events to supported xapi events

---

event_routing_backends/__init__.py
event_routing_backends/backends/events_router.py
event_routing_backends/processors/caliper/tests/test_caliper.py
event_routing_backends/processors/mixins/base_transformer.py
event_routing_backends/processors/mixins/base_transformer_processor.py
event_routing_backends/processors/xapi/tests/test_xapi.py

When errors such as when a backend isn't configured or there is no transformer for an event, bubbles up it causes the whole batch to get dumped to the dead letter queue. These changes cause those errors to be logged but otherwise just get dropped from the batch.
Error:
```
[2024-03-27 14:58:10,291: INFO/ForkPoolWorker-23] Event edx.course.enrollment.deactivated has been queued for batching. Queue size: 10
[2024-03-27 14:58:10,291: INFO/MainProcess] Task event_routing_backends.tasks.dispatch_bulk_events[c6ff920d-3d73-410d-ab73-bd41cfae0ec1] received
[2024-03-27 14:58:10,292: ERROR/ForkPoolWorker-23] Exception occurred while trying to bulk dispatch 10 events.
Traceback (most recent call last):
File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/backends/events_router.py", …
```

fix: Batching failures when individual event errors bubble up

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/management/commands/helpers/queued_sender.py
event_routing_backends/management/commands/recover_failed_events.py
event_routing_backends/management/commands/tests/test_recover_failed_events.py
event_routing_backends/management/commands/tests/test_transform_tracking_logs.py
event_routing_backends/settings/common.py
event_routing_backends/tests/test_settings.py
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
test_settings.py

**Description:** This PR updates the configuration to only use 1 setting entry for both backends.
This is a proposal, and depends on: https://github.com/openedx/event-tracking/pull/273

feat!: use one configuration for all backends

---

.github/workflows/ci.yml
Makefile
event_routing_backends/__init__.py
event_routing_backends/processors/xapi/tests/test_xapi.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.in
requirements/quality.txt
requirements/test.txt
setup.py
tox.ini

instructions.
1. Open page A
2. Do thing B
finished.

build: python 3.11 and 3.12 support

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/processors/xapi/event_transformers/forum_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.comment.created.json
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.response.created.json
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.thread.created.json
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.thread.deleted.json
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.thread.reported.json
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.thread.unreported.json
event_routing_backends/processors/xapi/tests/fixtures/expected/edx.forum.thread.viewed.json

It also adds the thread title to the thread events definition
instructions.
1. Open page A
2. Do thing B
finished.

feat: add discussion reference to comments and responses

---

docs/howto/how_to_bulk_transform.rst

**Description:** Docs update with new MINIO info
finished.

docs: Update command for MINIO

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/management/commands/helpers/queued_sender.py
event_routing_backends/management/commands/tests/test_transform_tracking_logs.py

**Description:** Check 'whitelist' and 'registry.mapping' options for event names to process. 'whitelist' was introduced in v9.0.0 but the tests and event check were not updated.
Tested all unit tests
Tested with (https://github.com/openedx/event-routing-backends/blob/84e09bc5fa7dde9ee2ed07fc04721c0799ad34e0/docs/howto/how_to_bulk_transform.rst#examples)
- LOCAL xapi
- LOCAL caliper
- MINIO
finished.

fix: Add support for whitelist and legacy registry options

---

event_routing_backends/helpers.py
event_routing_backends/tests/test_helpers.py

**Description:** Add the `lru_cache` decorator to the `get_anonymous_userid` and `get_course_overview` methods. Increased throughput up to 8 times on the `transform_tracking_log` command.
Closes #354 
```
Queued 16254 log lines, could not parse 0 log lines, skipped 1109 log lines, sent 1 batches.
60359691 function calls (55756047 primitive calls) in 98.828 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
6472/1    0.096    0.000   98.958   98.958 {built-in method builtins.exec}
1    0.000    0.000   98.958   98.958 manage.py:1(<module>)
1    0.000    0.000   90.905   90.905 __init__.py:439(execute_from_command_line)
1    0.000    0.000   90.904   90.904 __init__.py:353(execute)
1    0.000    0.000   90.844   90.844 …
```

perf: add lru cache for users and courses

---

event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py

instructions.
1. Open page A
2. Do thing B
finished.

fix: do not send duplicated events in batch

---

event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/tasks.py
event_routing_backends/utils/xapi_lrs_client.py

**Description:** Closes #460 
instructions.
1. Open page A
2. Do thing B
finished.

fix: catch json errors on empty responses from ralph

---

event_routing_backends/management/commands/tests/test_transform_tracking_logs.py
event_routing_backends/management/commands/transform_tracking_logs.py

**Description:** Sned the `chunk_size` parameter to libcloud directly instead of manually handling it, avoiding errors such as `ContentDecodeError` and `UnicodeDecodeError` on gzip files. Closes: #457 
instructions.
1. Open page A
2. Do thing B
finished.

fix: send chunk_size instead of manually handling it

---

docs/howto/how_to_bulk_transform.rst
event_routing_backends/backends/events_router.py
event_routing_backends/backends/tests/test_events_router.py
event_routing_backends/management/commands/helpers/queued_sender.py
event_routing_backends/management/commands/tests/test_transform_tracking_logs.py
event_routing_backends/management/commands/transform_tracking_logs.py

Introduced the --lrs-urls argument to allow specifying multiple LRS route URLs. This enhancement enables sending tracking logs exclusively to the designated LRSs, preventing data from being sent to all configured LRSs.
close #483
instructions.
1. Open page A
2. Do thing B
finished.
solutions, hacks, quick-and-dirty …

feat: add --lrs-urls option to transform_tracking_logs command

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/processors/tests/fixtures/current/problem_check(server).list_answers.json
event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server).list_answers.json

Maintain unicode characters in multi select problems during json dumps to match non-list responses
instructions.
1. Create a multi-select problem with answers that have unicode characters (è, á)
2. Submit response to the problem
3. Check xapi.problem_events , column `responses` and ensure unicode is still formatted correctly in the array
Current:
["Clart\u00e9", "Coh\u00e9rence", "Longueur"]
New:
["Clarté", "Cohérence", "Longueur"]
finished. …

fix: keep unicode characters in problem response list

---

CHANGELOG.rst
event_routing_backends/__init__.py
event_routing_backends/models.py
event_routing_backends/processors/mixins/base_transformer.py
test_utils/__init__.py

**Description:** In some cases the context user and the data user are different, such as when an instructor enrolls a learner through the instructor dashboard. This change ensures that the data user is checked first, since that should be the "actor" for our purposes. It also changes search order to look for user id before username for performance reasons.
Closes: #508 
1. Check out this branch
2. Enroll a new test user in a course using the instructor dashboard
3. Observe the tracking logs show different users in `context` and `data`
4. Confirm that the correct user (the new test user) is present in the xAPI statement and not the instructor
finished.
**Author concerns:**
It is possible that some events besides enrollments may …

fix: Change search order for users
